version: '3'
services:
  app:
    build:
      context: .
    entrypoint: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/saving
      - public-data:/saving/public
      - tmp-data:/saving/tmp
      - log-data:/saving/log
    networks:
      - saving-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
#    depends_on:
#      - db
#
#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#      MYSQL_DATABASE: fitO2_development
#    volumes:
#      - db-data:/var/lib/mysql
#    networks:
#      - saving-network

  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/saving/public
      - tmp-data:/saving/tmp
    ports:
      - 80:80
    depends_on:
      - app
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - saving-network
volumes:
  public-data:

  tmp-data:
  log-data:
  db-data:

networks:
  saving-network:
    external: true