version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundler install
          command: |
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

  test:
    docker:
      - image: circleci/ruby:3.0.0
      - image: circleci/mysql:5.5
        name: "db"
        environment:
          DB_USERNAME: root
          DB_DATABASE: saving_test
          DB_PASSWORD: ""
          DB_HOST: db
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: 127.0.0.1
      RAILS_ENV: test
    working_directory: ~/saving/src
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: setup database
          command: |
            sudo apt update
            sudo apt-get install default-mysql-client
      - run:
          name: execute sql
          command: mysql-ctl start
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: run test
          command: bundle exec rails test

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 34:98:98:c5:83:2a:c0:b1:94:a0:c2:56:2d:4c:0d:11
            - 08:a1:85:27:e7:83:c5:ae:68:8c:d2:3b:05:dc:82:70
      - run:
          name: Auto Deproy
          command: ssh ${USER_NAME}@${HOST_NAME} 'cd /saving && sudo git pull origin main'

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main