session:
  url: redis://localhost:6379
  # 20年間を秒数で表している　3600 * 24 * 365 * 2 = 630720000
  timeout: 630720000　
error_codes:
  unprocessable_entity: 422
  record_not_found: 2003
  unauthorized: 2004
  models:
    user:
      email:
        taken: 2000
        invalid: 2002
      password:
        too_short: 2001
