session:
  url: redis://localhost:6379
  timeout: 604800
error_codes:
  unprocessable_entity: 422
  record_not_found: 2003
  unauthorized: 2004
  models:
    user:
      email:
        taken: 2000
        invalid: 2002
      password:
        too_short: 2001
